{{- if ne .Values.relay.accessToken "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relay.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "relay.labels" . | nindent 4 }}
data:
  ASPM_ACCESS_TOKEN: {{ .Values.relay.accessToken | b64enc | quote }}
{{- end }}
